diff.astextplain.textconv=astextplain
filter.lfs.clean=git-lfs clean -- %f
filter.lfs.smudge=git-lfs smudge -- %f
filter.lfs.process=git-lfs filter-process
filter.lfs.required=true
http.sslbackend=openssl
http.sslcainfo=C:/Users/aluno.PEDAG/AppData/Local/Programs/Git/mingw64/ssl/certs/ca-bundle.crt
core.autocrlf=true
core.fscache=true
core.symlinks=false
core.editor="C:\\VisualStudioCode\\bin\\code" --wait
credential.helper=manager-core
pull.rebase=false
init.defaultbranch=main
credential.https://dev.azure.com.usehttppath=true
user.email=dominguesoliveiracarol@gmail.com
user.name=Carolina Domingues
core.repositoryformatversion=0
core.filemode=false
core.bare=false
core.logallrefupdates=true
core.symlinks=false
core.ignorecase=true
